### DISCUSSION TITLE
Processing documents via the API?

### DISCUSSION THREAD

**Discussion by jontstaz** [safevideo/autollm#100] [Q&A] [answered]
Hi, I like the idea of the API and I have played around with the examples for the regular script although there's not much documentation in terms of the API.

This is my `config.yaml`:
```yaml
version: '1.0'  # Version of this configuration file
tasks:
  - name: "summarize"
    system_prompt: "You are an expert ai assistant specialized in summarization."  # System prompt for this task
    vector_store_params:
      vector_store_type: "LanceDBVectorStore"
      uri: "tmp/lancedb"
      collection_name: "summarize"
    llm_params:
      model: "gpt-3.5-turbo"
    service_context_params:
      chunk_size: 1024
    query_engine_params:
      similarity_top_k: 5
    enable_cost_calculator: true
  - name: "qa"
    system_prompt: "You are a friendly ai assistant specialized in question answering."  # System prompt for this task
    vector_store_params:
      vector_store_type: "LanceDBVectorStore"
      uri: "tmp/lancedb"
      collection_name: "qa"
    llm_params:
      model: "gpt-4"
    service_context_params:
      chunk_size: 1024
    query_engine_params:
      similarity_top_k: 3
    enable_cost_calculator: false
```

And this is my api.py:
```py
import uvicorn

from autollm import AutoFastAPI

app = AutoFastAPI.from_config("config.yaml")

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
```

How can I load a GitHub Readme.md from a URL via this API? From the generated OpenAPI documentation itself, I can see there seem to be 3 available query params:
```
{
  "task": "summarize",
  "user_query": "Summarize the Readme.MD file from the provided Github Repo...,
  "streaming": false
}
```
Is it possible to somehow pass the Readme URL somehow? When I try to pass it within the user_query itself, it gives an error like: `"I'm sorry, but I cannot directly access external websites or specific GitHub repositories. However, if you provide me with the content of the README.md file from the GitHub repository, I can help you summarize it."`.

Thanks in advance
