### DISCUSSION TITLE
Very short answers

### DISCUSSION THREAD

**Discussion by seoeaa** [safevideo/autollm#135] [Q&A] [answered]
I don’t understand why he answers so briefly, the hint doesn’t help

**Comment by talhasarit** [comment, marked as answer]
Hello @seoeaa,

Thank you for bringing up your concern about the brevity of the answers. If you'd like to receive longer responses from the LLM, you can adjust the `max_tokens` parameter in your configuration. To be able to use this feature, please update `autollm` to latest version by using `pip install -U autollm`.

Please refer to our [`config.example.yaml`](https://github.com/safevideo/autollm/blob/main/examples/configs/config.example.yaml) file for a guide on setting this parameter and others:

```yaml
# config.example.yaml

# ... (other configurations)

# Parameters for the LLM
llm_params:
  model: "gpt-3.5-turbo"       # Model identifier
  max_tokens: 2048               # Increase this value for longer outputs
# ... (other configurations)
```

By setting the `max_tokens` to a higher value, you allow the system to generate more content, which should address the issue of brief answers.

Please try this adjustment and let us know if it improves the length and detail of the answers.
