### DISCUSSION TITLE
Example only using free Hugging Face inference and embeddings

### DISCUSSION THREAD

**Discussion by vanetreg** [safevideo/autollm#211] [Q&A] [answered]
Pls. create a working example which only uses free Hugging Face endpoints for both embeddings and completion.
I tried to tweak existing example using
**AutoQueryEngine.from_config()**
by the docs but it still uses OpenAI's endpoints, so I was wrong.
Probably others also would prefer this, without spending any money for OpenAI API :)

**Comment by talhasarit** [comment, marked as answer]
Hi @vanetreg, thank you for suggestion! I will definetely update our examples according your suggestion :) 

For quick solution, you can set your `llm_model` and `embed_model` parameters as Hugging Face models and you are good to go! If you have hosted it on Huggingface, you also should give the `llm_api` parameter as your hosted url:

```
tasks:
  - name: "qa"
    llm_model: "huggingface/WizardLM/WizardCoder-Python-34B-V1.0"
    llm_api_base: "https://my-endpoint.huggingface.cloud"
    embed_model: "huggingface/BAAI/bge-large-zh"  
```

also you might need to set your `HUGGINGFACE_API_KEY` env variable:

```python
os.environ['HUGGINGFACE_API_KEY'] = ...
```

Hope it helps. If you have any more suggestions or questions please share them as well.
